### ISSUE TITLE
sound problem

### ISSUE THREAD

**Issue by ctermiii** [R-a-s-c-a-l/Hackintosh-Dell-OptiPlex_7080MT#1]
hi there.
thanks for your hard work, your efi is pretty good.
my problem is : when I use original AppleALC (with alcid=67), I got sound but no dp sound.
when I found your efi,i use your applealc and fakeicd,and delete device properties of applealc, dp sound good but no motherboard sound. then I add alcid=67, it went back to motherboard but no dp sound .
how can motherboard and dp sound all work?

**Comment by ctermiii** [comment]
plus:without alcid=67,dp
 sound ok,hackintools can see acl3246 under sound tab,but there is no alc sound card in system preference panel.

**Comment by R-a-s-c-a-l** [comment]
It's my oversight. Now it's fixed. 😅

**Comment by ctermiii** [comment]
got it. I will have try lager.

**Comment by ctermiii** [comment]
it's ok now. 
I also add properties in my  config.plist , load your allele and faceicd kext.
all done.
thanks.

**Comment by R-a-s-c-a-l** [comment]
😁

**Comment by ctermiii** [comment]
I wonder how you can figure it out  and make these acpi patches? 
I am interested .

**Comment by R-a-s-c-a-l** [comment]
[ACPI_6_3_May16.pdf](https://github.com/R-a-s-c-a-l/Hackintosh-Dell-OptiPlex_7080MT/files/6252054/ACPI_6_3_May16.pdf) 😁

**Comment by ctermiii** [comment]
roger that.
studing now.
i mean how you can find 7080 has the hpet conflicts?

**Comment by R-a-s-c-a-l** [comment]
Because AppleHDA cannot load, only the AppleHDAController is loaded,

**Comment by R-a-s-c-a-l** [comment]
<img width="253" alt="截屏2021-04-03 下午6 59 21" src="https://user-images.githubusercontent.com/78466401/113476568-c4afad80-94ae-11eb-9152-2bdef15dbf5f.png"> like this.
 HPET is a legacy device that doesn't work in the new operating system,
