### ISSUE TITLE
acpi HPET

### ISSUE THREAD

**Issue by ctermiii** [R-a-s-c-a-l/Hackintosh-Dell-OptiPlex_7080MT#2]
hi there.
in your acpi patch ,I saw something about hpte,but nothing about HPET, is there a typo?

**Comment by R-a-s-c-a-l** [comment]
Set HPTE FieldUnit to Zero to disable HPET

**Comment by R-a-s-c-a-l** [comment]
![Uploading 518AC7C2-B6A6-4C37-B4A0-8447D6C72EB3.png…]()

**Comment by R-a-s-c-a-l** [comment]
<img width="486" alt="518AC7C2-B6A6-4C37-B4A0-8447D6C72EB3" src="https://user-images.githubusercontent.com/78466401/113392270-71aefb00-93c7-11eb-9300-4a9113dcd452.png">

**Comment by ctermiii** [comment]
thanks for reply, I saw it. but it's HPTE. not HPET. is it a typo?

**Comment by ctermiii** [comment]
sorry .I get it.

**Comment by ctermiii** [comment]
if I want a single acpi file , which part do I need? or can I place it in config.plist?
